
### Recuperar todas las peliculas
GET  http://localhost:1234/producto/categoria/1

### Recuperar todas las peliculas
GET http://localhost:1234/producto?id=Hogar

###Recuperar toda la pelicula por id
GET http://localhost:1234/producto/3

###Crear una categoria
POST http://localhost:1234/producto
Content-Type: application/json

{
    "nombre": "dasdas",
    "descripcion": " ",
    "precio": 100,
    "stock": 10,
    "categoriaID": 1
}

### Borrar una ferreteria
DELETE http://localhost:1234/producto/8

###Actualizar Categoria
PATCH http://localhost:1234/categoria/3
Content-Type: application/json

{
    "descripcion": "dasd",
    "precio": 100
}


###Recuperar todas las categorias por id
GET http://localhost:1234/categoria/2


### Post Categoria
POST http://localhost:1234/categoria
Content-Type: application/json

{
    "nombre": "ferremas",
    "descripcion": ""
}

### Borrar una categoria
DELETE http://localhost:1234/categoria/4

###Actualizar Categoria
PATCH http://localhost:1234/categoria/2
Content-Type: application/json

{
    "nombre": "Hogar",
    "descripcion": ""
}

###Crear una categoria
POST http://localhost:1234/producto
Content-Type: application/json

{
    "nombre": "dasdas",
    "descripcion": " ",
    "precio": 100,
    "stock": 10,
    "categoriaID": 1
}

### Borrar una ferreteria
DELETE http://localhost:1234/producto/8

###Actualizar Categoria
PATCH http://localhost:1234/producto/3
Content-Type: application/json

{
    "descripcion": "SADASD"
}


###Recuperar todas las marcas
GET http://localhost:1234/marca
=======
GET http://localhost:1234/marca


### Get ByPrecio

GET http://localhost:1234/producto/precio/1


### Venta

POST http://localhost:1234/webpay/createVenta
Content-Type: application/json

{
  "venta": {
    "fecha": "2024-06-01 00:00:00",
    "clienteID": 1,
    "estado": "CREATED"
  },
  "detallesVenta": [
    {
      "productoID": 1,
      "cantidad": 2,
      "precio": 1000
    },
    {
      "productoID": 2,
      "cantidad": 1,
      "precio": 500
    }
  ],
  "amount": 2500
}

### Venta

POST http://localhost:1234/webpay/comprar
Content-Type: application/json

{
  "clienteID": 1,
  "productos": [
    {
      "productoID": 1,
      "cantidad": 2,
      "precio": 100
    },
    {
      "productoID": 2,
      "cantidad": 1,
      "precio": 200
    }
  ]
}